<?php

namespace ContainerZjLRIB1;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailPostSendSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\MailPostSendSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\MailPostSendSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'MailPostSendSubscriber.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscriber\\MailPostSendSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\MailPostSendSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\MailPostSendSubscriber'] = new \App\EventSubscriber\MailPostSendSubscriber($a);
    }
}
