<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DetalleActividad extends \App\Entity\DetalleActividad implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'URL' => [parent::class, 'URL', null],
        "\0".parent::class."\0".'actividad' => [parent::class, 'actividad', null],
        "\0".parent::class."\0".'alumno' => [parent::class, 'alumno', null],
        "\0".parent::class."\0".'espacio' => [parent::class, 'espacio', null],
        "\0".parent::class."\0".'fecha_hora_fin' => [parent::class, 'fecha_hora_fin', null],
        "\0".parent::class."\0".'fecha_hora_inicio' => [parent::class, 'fecha_hora_inicio', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'ponentes' => [parent::class, 'ponentes', null],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null],
        'URL' => [parent::class, 'URL', null],
        'actividad' => [parent::class, 'actividad', null],
        'alumno' => [parent::class, 'alumno', null],
        'espacio' => [parent::class, 'espacio', null],
        'fecha_hora_fin' => [parent::class, 'fecha_hora_fin', null],
        'fecha_hora_inicio' => [parent::class, 'fecha_hora_inicio', null],
        'id' => [parent::class, 'id', null],
        'ponentes' => [parent::class, 'ponentes', null],
        'titulo' => [parent::class, 'titulo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
