<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'activationToken' => [parent::class, 'activationToken', null],
        "\0".parent::class."\0".'apellido1' => [parent::class, 'apellido1', null],
        "\0".parent::class."\0".'apellido2' => [parent::class, 'apellido2', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'foto' => [parent::class, 'foto', null],
        "\0".parent::class."\0".'grupos' => [parent::class, 'grupos', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'nick' => [parent::class, 'nick', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'activationToken' => [parent::class, 'activationToken', null],
        'apellido1' => [parent::class, 'apellido1', null],
        'apellido2' => [parent::class, 'apellido2', null],
        'email' => [parent::class, 'email', null],
        'foto' => [parent::class, 'foto', null],
        'grupos' => [parent::class, 'grupos', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'nick' => [parent::class, 'nick', null],
        'nombre' => [parent::class, 'nombre', null],
        'password' => [parent::class, 'password', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
