<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Actividad extends \App\Entity\Actividad implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descripcion' => [parent::class, 'descripcion', null],
        "\0".parent::class."\0".'detalleActividads' => [parent::class, 'detalleActividads', null],
        "\0".parent::class."\0".'evento' => [parent::class, 'evento', null],
        "\0".parent::class."\0".'fecha_hora_fin' => [parent::class, 'fecha_hora_fin', null],
        "\0".parent::class."\0".'fecha_hora_inicio' => [parent::class, 'fecha_hora_inicio', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'tipo' => [parent::class, 'tipo', null],
        'descripcion' => [parent::class, 'descripcion', null],
        'detalleActividads' => [parent::class, 'detalleActividads', null],
        'evento' => [parent::class, 'evento', null],
        'fecha_hora_fin' => [parent::class, 'fecha_hora_fin', null],
        'fecha_hora_inicio' => [parent::class, 'fecha_hora_inicio', null],
        'id' => [parent::class, 'id', null],
        'tipo' => [parent::class, 'tipo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
