<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \App\Entity\Evento implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'actividads' => [parent::class, 'actividads', null],
        "\0".parent::class."\0".'fecha_fin' => [parent::class, 'fecha_fin', null],
        "\0".parent::class."\0".'fecha_inicio' => [parent::class, 'fecha_inicio', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'titulo' => [parent::class, 'titulo', null],
        'actividads' => [parent::class, 'actividads', null],
        'fecha_fin' => [parent::class, 'fecha_fin', null],
        'fecha_inicio' => [parent::class, 'fecha_inicio', null],
        'id' => [parent::class, 'id', null],
        'titulo' => [parent::class, 'titulo', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
