<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4ZeE9pR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4ZeE9pR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4ZeE9pR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4ZeE9pR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4ZeE9pR\App_KernelDevDebugContainer([
    'container.build_hash' => '4ZeE9pR',
    'container.build_id' => 'b026c2c5',
    'container.build_time' => 1716408641,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4ZeE9pR');
